version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    environment:
      NODE_ENV: development
    volumes:
      - ./server:/app
      - /app/node_modules
    develop:
      watch:
        - action: sync
          path: ./server
          target: /app
          ignore:
            - node_modules/
            - dist/
            - .git/
        - action: rebuild
          path: ./server/package.json

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
    environment:
      NODE_ENV: development
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    develop:
      watch:
        - action: sync
          path: ./client
          target: /app
          ignore:
            - node_modules/
            - .next/
            - .git/
        - action: rebuild
          path: ./client/package.json
